### ISSUE TITLE
JSON Data encoding

### ISSUE THREAD

**Issue by dashawk** [carlo/jquery-base64#4]
Got an error while encoding a json string.

var regDetails = JSON.stringify(data);
var json = $.base64.encode(regDetails);

WHERE data is a valid json data.

Uncaught INVALID_CHARACTER_ERR: DOM Exception 5

**Comment by gala132** [comment]
Hi!
It is a late answer, but it happens because of this if block.
https://github.com/carlo/jquery-base64/blob/master/jquery.base64.js#L135-L137
